### ISSUE TITLE
God de mais

### ISSUE THREAD

**Issue by Rafael-Martins** [sShayron/csgo-cfgs#1]
Mt god vei, valeu ai

**Comment by guilhermelimak** [comment]
ja eh semipro esse mlk?

**Comment by Rafael-Martins** [comment]
era o tompero que faltava essas conf ai

**Comment by sShayron** [comment]
IHJOP0ESAOPHIESAHIOPPEHIOSAIOPHEASOPHIDHIPRSAJO I´HPDEASIK´HJPRASDHIO´DIJPR´HS AARDSHOPÍARDS´HIOADRSHIOPÁDRSHIJOP´RDSSAIOP´H

**Comment by sShayron** [comment]
FALTA TOMPERO
